# Generated by Django 3.0.4 on 2020-04-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandas_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covid',
            old_name='deaths',
            new_name='death',
        ),
    ]
